# Base Docker Compose configuration
# Use with: docker compose -f compose.yml -f compose.dev.yml up (for dev)
#          docker compose -f compose.yml -f compose.prod.yml up (for prod)

services:
  ludora-api:
    build:
      context: .
      dockerfile: docker/nest-api/Dockerfile
    container_name: ludora-api
    environment:
      - DOPPLER_TOKEN
    networks:
      - ludora-network
    depends_on:
      - ludora-db

  ludora-db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      - DOPPLER_TOKEN
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ludora-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ludora-network

volumes:
  postgres-data:
  grafana-data:
  prometheus-data:

networks:
  ludora-network:
    driver: bridge
