services:
  nest:
    build:
      context: .
      dockerfile: docker/nest-api/Dockerfile
    container_name: nest
    environment:
      - DOPPLER_TOKEN
    volumes:
      - ./src:/usr/src/app/src
      - ./pnpm-lock.yaml:/usr/src/app/.pnpm-lock.yaml
      - ./package.json:/usr/src/app/package.json
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - '5432:5432'
    environment:
      - DOPPLER_TOKEN
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
