export enum scope {
  PAST = 'PAST',
  UPCOMING = 'UPCOMING',
  ALL = 'ALL',
}

export enum Sport {
  BASKETBALL = 'BASKETBALL',
  FOOTBALL = 'FOOTBALL',
  TENNIS = 'TENNIS',
  VOLLEYBALL = 'VOLLEYBALL',
  PADDEL = 'PADDEL',
  BADMINTON = 'BADMINTON',
  PING_PONG = 'PING-PONG',
}
