/**
 * @description Every notification type that the user can receive
 */
export enum NotificationType {
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',
  SESSION_INVITATION = 'SESSION_INVITATION',
  SESSION_UPDATED = 'SESSION_UPDATED',
  SESSION_CANCELLED = 'SESSION_CANCELLED',
  SESSION_REMINDER = 'SESSION_REMINDER',
  NEW_MESSAGE = 'NEW_MESSAGE',
  GENERAL = 'GENERAL',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
}
